### ISSUE TITLE
Example of minimal server

### ISSUE THREAD

**Issue by isberg** [kbertalan/tyttp#11]
Hi, it would be really helpful if there existed a minimal example of a server. I get the echo test code to run, but I fail to make it respond to a call from curl or a web browser. 
Friendly /Jonas

**Comment by kbertalan** [comment]
Hi @isberg ,

I have just updated `README.md` and the example at `adapter-node/src/Main.idr`. I also added a Dockerfile and instructions in the readme file, which describes how I am currently running the project, but it also should be usable for others.

Please note, that all adapter-node tests should be functional, you should be able to run them and test them after removing the HTTP requests after starting the server, which validates the server behavior.

I also suggest for checking the test under https://github.com/kbertalan/tyttp-json/blob/main/tests/json/JSONServer.idr which showcases JSON body parsing and JSON responses.

Let me know if you have any questions.

**Comment by isberg** [comment]
Thanks @kbertalan! Running adapter-node in docker using your Dockerfile certainly works. However, all the tests seems to fail in my own docker container (which also is much less elegant), so I just have to rebase my own Dockerfile on yours and all should be fine. The updated README together with the Dockerfile make everything much clearer to me. Feel free to close this issue. :-)

**Comment by isberg** [comment]
If someone else arrives here with the some problem I have, I can just mention that it works fine to clone tyttp and reference a local copy of tyttp-adapter-node in a pack.toml file and then happily `import TyTTP.Adapter.Node.HTTP` in your own file:

```toml
[custom.all.tyttp-adapter-node]
type = "local"
path = "<path>/tyttp/adapter-node/"
ipkg = "tyttp-adapter-node.ipkg"
test = "test/test.ipkg"
```

**Comment by isberg** [comment]
> Hi @isberg ,
> 
> I have just updated `README.md` and the example at `adapter-node/src/Main.idr`. I also added a Dockerfile and instructions in the readme file, which describes how I am currently running the project, but it also should be usable for others.
> 
> Please note, that all adapter-node tests should be functional, you should be able to run them and test them after removing the HTTP requests after starting the server, which validates the server behavior.
> 
> I also suggest for checking the test under https://github.com/kbertalan/tyttp-json/blob/main/tests/json/JSONServer.idr which showcases JSON body parsing and JSON responses.
> 
> Let me know if you have any questions.

Hi @kbertalan,
  I am trying to get the JSONServer example to work, but `RecordFromJSON` and `RecordToJSON` is reported as `Undefined name` to me, and cannot find any source code or documentation anywhere about these. I find FromJSON and ToJSON in the json package and I guess the line `%runElab derive "Example" [Generic, Meta, Show, Eq, RecordToJSON, RecordFromJSON]` could be even more magic than I think. Any word of advice? 

I get above errors when I run the JSONServer code in my own package/project, but it also failed for me when I cloned tyttp-json and tried to run the code from its original location, but then I think it choked when importing `TyTTP.Adapter.Node.HTTP` and `TyTTP.Adapter.Node.URI`, which is a bit frustrating because I thought I had got the hang of handling those. Any chance of a second `Dockerfile` and/or a few more lines in the documentation over at `tyttp-json`? :-)

**Comment by kbertalan** [comment]
As I can see I was quite optimistic about the state of tyttp-json state.
I had not really working on these projects in the last 1.5-2 years, so they started to fail.

I had started to experiment with the tyttp-json build and tests, and they are also not working for me. Currently it needs installation of the dependencies, which also includes `tyttp-adapter-node`.

For quick experiment on your side, I suggest to run `pack install contrib test tyttp tyttp-adapter-node promise tyttp-json json sop elab-util apache-mime-types node` in the `tyttp` source folder first, then you might be able to run the tests / code in `tyttp-json`.

To make the experience less manual, I have opened https://github.com/stefan-hoeck/idris2-pack-db/pull/145 to make `tyttp-adapter-node` available through pack without needing the source code of `tyttp`.

After that I will be able to check whether there are any backward incompatible changes in the dependencies, which needs fixes in `tyttp-json` and its tests.

**Comment by isberg** [comment]
Thanks @kbertalan, I really appreciate it. 🙏

**Comment by kbertalan** [comment]
As I suspected, there was a change in the `json` dependency which was broken in the JSONServer test.
You can find the updated and working version at https://github.com/kbertalan/tyttp/blob/main/json/tests/json/server/JSONServer.idr

In addition, I will remove the `tyttp-json` repository soon, as I moved that project into this repository. In the upcoming days, I will update pack db too with the location change of `tyttp-json`.

**Comment by kbertalan** [comment]
The mentioned changes are now available in the pack db.
